# Generated by Django 2.2.6 on 2019-10-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=15)),
                ('company_name', models.CharField(max_length=50)),
                ('license_key', models.CharField(default='sizbUiOglz3zbnzPFxqw', max_length=20, unique=True)),
                ('domain', models.CharField(max_length=100)),
                ('expire', models.DateTimeField(auto_now=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Packages')),
                ('tv_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Tv')),
            ],
        ),
    ]
