# Generated by Django 2.2.6 on 2019-10-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='license_key',
            field=models.CharField(default='xHQvBJtNeMpAV2OxoJLu', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
