# Generated by Django 2.2.6 on 2019-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20191002_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='abir@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='license_key',
            field=models.CharField(default='fpZWKTsHXWJSzyXbOLww', max_length=20, unique=True),
        ),
    ]
