# Generated by Django 2.2.6 on 2019-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20191002_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='license_key',
            field=models.CharField(default='qVvBY6M4FpRxO2G3qejY', max_length=20, unique=True),
        ),
    ]
