# Generated by Django 2.2.6 on 2019-10-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20191002_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='license_key',
            field=models.CharField(default='r7YwYe9tVv1iNkgIiFNF', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Packages'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tv_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Tv'),
        ),
    ]
