# Generated by Django 2.2.6 on 2019-10-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20191002_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='license_key',
            field=models.CharField(default='Hi3M73OGofY9tB0br9oL', max_length=20, unique=True),
        ),
    ]
